#!/usr/bin/env node
const util = require("util");
const childProcessExec = require("child_process").exec;
const fs = require("fs");

const exec = util.promisify(childProcessExec);
const TASK_REGEX = new RegExp(/TICKET_PREFIX-\d+/, 'i');

const message = fs.readFileSync(process.argv[2], "utf8").trim();

console.log("Suffixing your commit msg with your ticket name");
makeCommitMsg();

async function makeCommitMsg() {
  const branches = await exec("git branch");
  const current = branches.stdout.split("\n").find((b) => b.charAt(0) === "*");
  const task_name = current.match(TASK_REGEX)[0];
  
  if(task_name){
    const msg = `${message} \n[${task_name}]`;
    
    fs.writeFileSync(process.argv[2], msg);
  }

  process.exit(0);
}
